[phases.setup]
aptPkgs = ["wget", "gnupg", "ca-certificates"]
nixPkgs = ["python310"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install-deps",
    "playwright install chromium"
]

[start]
cmd = "python main.py"
